
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LexicalAnalyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_NUM = 19;
  public static final int TK_LPAREN = 7;
  public static final int TK_GREATER = 11;
  public static final int TK_LESS = 12;
  public static final int TK_DIV = 5;
  public static final int TK_MENOS = 3;
  public static final int TK_EQUAL = 13;
  public static final int TK_DIFFERENT = 14;
  public static final int TK_KEYWORD_B = 23;
  public static final int TK_KEYWORD_A = 22;
  public static final int TK_RKEY = 18;
  public static final int TK_MAS = 2;
  public static final int EOF = 0;
  public static final int TK_ENTER = 9;
  public static final int TK_FUNCTION = 21;
  public static final int TK_LKEY = 17;
  public static final int TK_AND = 15;
  public static final int TK_OR = 16;
  public static final int error = 1;
  public static final int TK_PYC = 10;
  public static final int TK_TYPE = 24;
  public static final int TK_MAIN = 25;
  public static final int TK_RPAREN = 8;
  public static final int TK_ID = 20;
  public static final int TK_ASSIGN = 6;
  public static final int TK_POR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_MAS",
  "TK_MENOS",
  "TK_POR",
  "TK_DIV",
  "TK_ASSIGN",
  "TK_LPAREN",
  "TK_RPAREN",
  "TK_ENTER",
  "TK_PYC",
  "TK_GREATER",
  "TK_LESS",
  "TK_EQUAL",
  "TK_DIFFERENT",
  "TK_AND",
  "TK_OR",
  "TK_LKEY",
  "TK_RKEY",
  "TK_NUM",
  "TK_ID",
  "TK_FUNCTION",
  "TK_KEYWORD_A",
  "TK_KEYWORD_B",
  "TK_TYPE",
  "TK_MAIN"
  };
}

